site_name: Grompt - AI Prompt Engineering Platform
site_description: Transform unstructured ideas into clean, effective prompts for AI models
site_author: Rafa Mori
site_url: https://grompt.kubex.world
repo_name: kubex-ecosystem/grompt
repo_url: https://github.com/kubex-ecosystem/grompt
docs_dir: ../../docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: deep purple
      accent: purple
      toggle: {icon: material/brightness-7, name: Dark mode}
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle: {icon: material/brightness-4, name: Light mode}
  font: {text: Roboto, code: Roboto Mono}
  icon: {logo: material/brain}

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji: {emoji_index: !!python/name:material.extensions.emoji.twemoji}

plugins: [search, minify]

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quick-start.md
  - Features:
      - BYOK Support: features/byok.md
      - Resilience Modes: features/resilience.md
  - About:
      - License: about/license.md
