site_name: Grompt
site_url: https://rafa-mori.github.io/grompt/
site_description: "A powerful CLI tool for managing and transforming prompts with advanced features and dynamic notifications"
site_author: "Rafael Mori"

repo_name: "rafa-mori/grompt"
repo_url: https://github.com/rafa-mori/grompt

docs_dir: ../../docs

theme:
  name: material
  palette:
    primary: "indigo"
    accent: "indigo"
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.tabs.sticky.scroll
    - navigation.tabs.sticky.scroll.offset: 64
    - navigation.tabs.sticky.scroll.offset.mobile: 0
    - navigation.tabs.sticky.scroll.offset.desktop: 64
    - navigation.tabs.sticky.scroll.offset.tablet: 64
    - search.highlight
    - search.share
    - search.suggest
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - toc:
      permalink: True
      title: On this page
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - smarty
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: rafa-mori
      repo: grompt
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Início: index.md
  - Primeiros Passos:
      - Instalação: getting-started/installation.md
      - Início Rápido: getting-started/quickstart.md
  - Guia do Usuário:
      - Comandos CLI: user-guide/cli-commands.md
      - Configuração: user-guide/configuration.md
      - Exemplos de Uso: user-guide/usage-examples.md
      - API Reference: user-guide/api-reference.md
  - Desenvolvimento:
      - Contribuindo: development/contributing.md
      - Solução de Problemas: development/troubleshooting.md
      - Arquitetura: development/architecture.md
  - Comunidade:
      - Código de Conduta: community/code-of-conduct.md
      - Suporte: community/support.md
      - Autores: community/authors.md
  - Informações do Projeto:
      - Licença: project-info/license.md
      - Aviso Legal: project-info/notice.md
      - Política de Segurança: project-info/security.md
      - Changelog: project-info/changelog.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rafa-mori/grompt
      name: Grompt on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rafa-mori/
      name: Rafael Mori on LinkedIn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/faelOmori
      name: Rafael Mori on Twitter
  version:
    provider: mike
  analytics:
    provider: google
    property: ${G-7HLY17F3DK}
# plugins:
#   - search:
#       lang: en
#   - git-revision-date-localized:
#       type: datetime
#       timezone: America/Sao_Paulo
#       locale: en
#       fallback_to_build_date: true
