name: Documentation Deploy

on:
  push:
    tags:
      - "v*.*.*"
    branches: [ main ]
    paths:
      - 'support/docs/**'
      - 'docs/**'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'support/docs/**'
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  NON_INTERACTIVE: true
  FORCE: y
  CI: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install MkDocs and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
          pip install mkdocs-git-revision-date-localized-plugin
          pip install pymdown-extensions

      - name: Copy files to docs directory
        run: |
          # Copiar arquivos do repositório para a estrutura de docs
          mkdir -p support/docs/docs/project-info

          # Copiar arquivos principais
          cp README.md support/docs/docs/project-info/readme-en.md
          cp docs/README.pt-BR.md support/docs/docs/project-info/readme-pt-br.md
          cp LICENSE support/docs/docs/project-info/license.md
          cp NOTICE.md support/docs/docs/project-info/notice.md
          cp SECURITY.md support/docs/docs/project-info/security.md
          cp docs/CONTRIBUTING.md support/docs/docs/development/contributing-original.md

          # Criar arquivo de changelog se não existir
          if [ ! -f support/docs/docs/project-info/changelog.md ]; then
            echo "# Changelog" > support/docs/docs/project-info/changelog.md
            echo "" >> support/docs/docs/project-info/changelog.md
            echo "Consulte o [histórico de releases](https://github.com/rafa-mori/grompt/releases) para ver todas as mudanças." >> support/docs/docs/project-info/changelog.md
          fi

          # Criar páginas que faltam se não existirem
          mkdir -p support/docs/docs/user-guide
          mkdir -p support/docs/docs/community
          mkdir -p support/docs/docs/development

          # API Reference
          if [ ! -f support/docs/docs/user-guide/api-reference.md ]; then
            echo "# API Reference" > support/docs/docs/user-guide/api-reference.md
            echo "" >> support/docs/docs/user-guide/api-reference.md
            echo "Documentação da API em desenvolvimento." >> support/docs/docs/user-guide/api-reference.md
          fi

          # Support page
          if [ ! -f support/docs/docs/community/support.md ]; then
            echo "# Suporte" > support/docs/docs/community/support.md
            echo "" >> support/docs/docs/community/support.md
            echo "Para suporte, visite nossas [GitHub Issues](https://github.com/rafa-mori/grompt/issues)." >> support/docs/docs/community/support.md
          fi

          # Authors page
          if [ ! -f support/docs/docs/community/authors.md ]; then
            echo "# Autores" > support/docs/docs/community/authors.md
            echo "" >> support/docs/docs/community/authors.md
            echo "## Criador Principal" >> support/docs/docs/community/authors.md
            echo "- **Rafael Mori** - [@rafa-mori](https://github.com/rafa-mori)" >> support/docs/docs/community/authors.md
            echo "" >> support/docs/docs/community/authors.md
            echo "## Contribuidores" >> support/docs/docs/community/authors.md
            echo "Veja a lista completa de [contribuidores](https://github.com/rafa-mori/grompt/contributors)." >> support/docs/docs/community/authors.md
          fi

          # Architecture page
          if [ ! -f support/docs/docs/development/architecture.md ]; then
            echo "# Arquitetura" > support/docs/docs/development/architecture.md
            echo "" >> support/docs/docs/development/architecture.md
            echo "Documentação da arquitetura em desenvolvimento." >> support/docs/docs/development/architecture.md
          fi

          # Troubleshooting page
          if [ ! -f support/docs/docs/development/troubleshooting.md ]; then
            echo "# Solução de Problemas" > support/docs/docs/development/troubleshooting.md
            echo "" >> support/docs/docs/development/troubleshooting.md
            echo "Guia de solução de problemas em desenvolvimento." >> support/docs/docs/development/troubleshooting.md
          fi

      - name: Build documentation
        run: |
          cd support/docs
          mkdocs build --verbose

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: support/docs/site

  # Deployment job
  deploy:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
